baseURL = "https://p0shkatz.github.io/"
languageCode = "en-us"
title = "p0shkatz.github.io"
theme = "coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[params]
    author = "Michael Garrison"
    description = "p0shkatz's pages"
    keywords = "blog,developer,infosec"
    info = "Pen Testing | Red Teaming | Security Research"
    avatarurl = "images/ivv3_3ao_400x400.jpg"
    footercontent = "Making and breaking it, and silly observations along the way"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/p0shkatz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/p0shkatz/"
[[params.social]]
	name = "Keybase"
	icon = "fab fa-keybase fa-2x"
	weight = 3
	url = "https://keybase.io/p0shkatz"
[[params.social]]
	name = "Slack"
	icon = "fab fa-slack fa-2x"
	weight = 4
	url = "https://bloodhoundhq.slack.com"
	
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/"
